package shared;
import javax.swing.JOptionPane;


/**
 *
 * @author lehuy
 */
public class RegisterForm extends javax.swing.JPanel {
    private final NetworkManager network;
    private final ClientMainFrm mainFrm;

    public RegisterForm(ClientMainFrm mainFrm, NetworkManager network) {
        initComponents();
        this.network = network;
        this.mainFrm = mainFrm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Khởi tạo các Component đã khai báo
        jLabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField(); // Name
        jTextField2 = new javax.swing.JTextField(); // Username
        jTextField3 = new javax.swing.JTextField(); // Password
        jTextField4 = new javax.swing.JTextField(); // Confirm password
        jButton1 = new javax.swing.JButton();

        // 1. Thiết lập Text cho các Component
        jLabel0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // Tiêu đề lớn hơn
        jLabel0.setText("Registration Form");
        
        jLabel1.setText("Name");
        jLabel2.setText("Username");
        jLabel3.setText("Password");
        jLabel4.setText("Confirm password");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        // 2. Thiết lập Bố cục (Layout)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        
        // --- BỐ CỤC CHIỀU NGANG (HORIZONTAL GROUP) ---
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                // Căn giữa Tiêu đề (jLabel0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            
            // Căn giữa nhóm input (4 hàng, 2 cột)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    // Hàng 1 (Name)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    // Hàng 2 (Username)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    // Hàng 3 (Password)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    // Hàng 4 (Confirm Password)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            
            // Căn giữa Nút Đăng ký (jButton1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        // --- BỐ CỤC CHIỀU DỌC (VERTICAL GROUP) ---
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                // Tiêu đề
                .addGap(20, 20, 20)
                .addComponent(jLabel0)
                
                // Khoảng trống linh hoạt để căn giữa khối input theo chiều dọc
                .addGap(30, 30, 30) // Khoảng cách giữa các hàng 

                // Hàng 1 (Name)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(10, 10, 10) // Khoảng cách giữa các hàng
                
                // Hàng 2 (Username)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(10, 10, 10) // Khoảng cách giữa các hàng
                
                // Hàng 3 (Password)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                .addGap(10, 10, 10) // Khoảng cách giữa các hàng
                
                // Hàng 4 (Confirm Password)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                
                // Khoảng cách giữa input cuối và nút Register
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                
                // Nút Đăng ký
                .addComponent(jButton1)
                
                // Khoảng trống dưới cùng
                .addGap(20, 20, 20))
        );    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String name = jTextField1.getText().trim();
       String username = jTextField2.getText().trim();
       String password = jTextField3.getText().trim();
       String confirmPassword = jTextField4.getText().trim();
       
       if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
           return;
       }
       if (!password.equals(confirmPassword)) {
           JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp");
           return;
       }
       
       try {
           Player player = new Player(name, username, password);
           ObjectSentReceived req = new ObjectSentReceived("Register", player);
           network.send(req);
           
           ObjectSentReceived resp = network.receive();
           if("Register".equals(resp.getType())) {
               boolean status = (Boolean) resp.getObj();
               if(status) {
                   JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
                   mainFrm.showLoginPanel();
               } else {
                   JOptionPane.showMessageDialog(this, "Đăng ký thất bại!");
               }
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}